apiVersion: 3
dataDisplay:
  textFormats:
    layout-full: 
      method: layoutFull
    layout-noremarks: 
      method: layoutNoRemarks
    layout-nonotes: 
      method: layoutNoNotes
    layout-nonorig: 
      method: layoutNonOrig
    layout-remarks:
      method:  layoutRemarks
    layout-notes:
      method:  layoutNotes
    layout-orig:
      method:  layoutOrig
docs:
  docPage: about
  featureBase: 'https://github.com/{org}/{repo}/blob/master/docs/transcription{docExt}'
  featurePage: ''
interfaceDefaults: {}
provenanceSpec:
  corpus: 'General Missives Dutch East India Company 1600-1800'
  doi: 10.5281/zenodo.4011801
  version: "1.0e"
  extraData: ner
  webBase: http://resources.huygens.knaw.nl/retroboeken/generalemissiven
  webHint: Show this document on Huygens
  webFeature: weblink
  webUrl: '{webBase}/#page=<2>&source=<1>'
  webOffset:
    2:
      1: 23
      2: 13
      3: 13
      4: 15
      5: 15
      6: 15
      7: 13
      8: 11
      9: 13
      10: 11
      11: 11
      12: 11
      13: 11
typeDisplay: {}
