versionSrc: "2020-09-10"
versionTf: "0.4"

name: Generale Missiven
title: Generale Missieven van Gouverneurs-Generaal en Raden aan Heren XVII der Verenigde Oostindische Compagnie
editor: Dr. W. Ph. Coolhaas, Dr. J. van Goor, Dr. J.E. Schooneveld-Oosterling, Dr. H.K. s'Jacob
published: Martinus Nijhoff (1960-1985), Bureau der Rijkscommissie voor Vaderlandse Geschiedenis (1988), Instituut voor Nederlandse Geschiedenis (1997, 2004-2007)
period: 1610-1761
language: nld
institute: KNAW/HuygensING
project: CLARIAH WP6 Use Case 1
researcher: Lodewijk Petram
converters: Sophie Arnoult, Jesse de Does (TEI), Dirk Roorda (Text-Fabric)
sourceFormat: TEI

